# Auto-generated metadata dictionary
NCC_indices_info = {
  "NCC_ATM1": {
    "standard_name": "Northern Hemisphere Subtropical High Area Index ",
    "short_name": "NCC_ATM1",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_1",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Subtropical High Area Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM2": {
    "standard_name": "North African Subtropical High Area Index ",
    "short_name": "NCC_ATM2",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_2",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African Subtropical High Area Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM3": {
    "standard_name": "North African-North Atlantic-North American Subtropical High Area Index ",
    "short_name": "NCC_ATM3",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_3",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African-North Atlantic-North American Subtropical High Area Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM4": {
    "standard_name": "Indian Subtropical High Area Index",
    "short_name": "NCC_ATM4",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_4",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Indian Subtropical High Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM5": {
    "standard_name": "Western Pacific Subtropical High Area Index",
    "short_name": "NCC_ATM5",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_5",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Western Pacific Subtropical High Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM6": {
    "standard_name": "Eastern Pacific Subtropical High Area Index",
    "short_name": "NCC_ATM6",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_6",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Eastern Pacific Subtropical High Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM7": {
    "standard_name": "North American Subtropical High Area Index",
    "short_name": "NCC_ATM7",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_7",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American Subtropical High Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM8": {
    "standard_name": "Atlantic Subtropical High Area Index",
    "short_name": "NCC_ATM8",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_8",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Atlantic Subtropical High Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM9": {
    "standard_name": "South China Sea Subtropical High Area Index",
    "short_name": "NCC_ATM9",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_9",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "South China Sea Subtropical High Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM10": {
    "standard_name": "North American-Atlantic Subtropical High Area Index",
    "short_name": "NCC_ATM10",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_10",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American-Atlantic Subtropical High Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM11": {
    "standard_name": "Pacific Subtropical High Area Index ",
    "short_name": "NCC_ATM11",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_11",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Pacific Subtropical High Area Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM12": {
    "standard_name": "Northern Hemisphere Subtropical High Intensity Index",
    "short_name": "NCC_ATM12",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_12",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM13": {
    "standard_name": "North African Subtropical High Intensity Index",
    "short_name": "NCC_ATM13",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_13",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM14": {
    "standard_name": "North African-North Atlantic-North American Subtropical High Intensity Index",
    "short_name": "NCC_ATM14",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_14",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African-North Atlantic-North American Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM15": {
    "standard_name": "Indian Subtropical High Intensity Index",
    "short_name": "NCC_ATM15",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_15",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Indian Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM16": {
    "standard_name": "Western Pacific Subtropical High Intensity Index",
    "short_name": "NCC_ATM16",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_16",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Western Pacific Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM17": {
    "standard_name": "Eastern Pacific Subtropical High Intensity Index",
    "short_name": "NCC_ATM17",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_17",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Eastern Pacific Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM18": {
    "standard_name": "North American Subtropical High Intensity Index",
    "short_name": "NCC_ATM18",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_18",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM19": {
    "standard_name": "North Atlantic Subtropical High Intensity Index",
    "short_name": "NCC_ATM19",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_19",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North Atlantic Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM20": {
    "standard_name": "South China Sea Subtropical High Intensity Index",
    "short_name": "NCC_ATM20",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_20",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "South China Sea Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM21": {
    "standard_name": "North American-North Atlantic Subtropical High Intensity Index",
    "short_name": "NCC_ATM21",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_21",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American-North Atlantic Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM22": {
    "standard_name": "Pacific Subtropical High Intensity Index",
    "short_name": "NCC_ATM22",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_22",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Pacific Subtropical High Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM23": {
    "standard_name": "Northern Hemisphere Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM23",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_23",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM24": {
    "standard_name": "North African Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM24",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_24",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM25": {
    "standard_name": "North African-North Atlantic-North American Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM25",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_25",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African-North Atlantic-North American Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM26": {
    "standard_name": "Indian Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM26",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_26",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Indian Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM27": {
    "standard_name": "Western Pacific Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM27",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_27",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Western Pacific Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM28": {
    "standard_name": "Eastern Pacific Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM28",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_28",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Eastern Pacific Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM29": {
    "standard_name": "North American Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM29",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_29",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM30": {
    "standard_name": "Atlantic Sub Tropical High Ridge Position Index",
    "short_name": "NCC_ATM30",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_30",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Atlantic Sub Tropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM31": {
    "standard_name": "South China Sea Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM31",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_31",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "South China Sea Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM32": {
    "standard_name": "North American-North Atlantic Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM32",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_32",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American-North Atlantic Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM33": {
    "standard_name": "Pacific Subtropical High Ridge Position Index",
    "short_name": "NCC_ATM33",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_33",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Pacific Subtropical High Ridge Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM34": {
    "standard_name": "Northern Hemisphere Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM34",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_34",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM35": {
    "standard_name": "North African Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM35",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_35",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM36": {
    "standard_name": "North African-North Atlantic-North American Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM36",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_36",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North African-North Atlantic-North American Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM38": {
    "standard_name": "Western Pacific Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM38",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_38",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Western Pacific Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM39": {
    "standard_name": "Eastern Pacific Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM39",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_39",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Eastern Pacific Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM40": {
    "standard_name": "North American Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM40",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_40",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM41": {
    "standard_name": "Atlantic Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM41",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_41",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Atlantic Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM43": {
    "standard_name": "North American-Atlantic Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM43",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_43",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American-Atlantic Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM44": {
    "standard_name": "Pacific Subtropical High Northern Boundary Position Index",
    "short_name": "NCC_ATM44",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_44",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Pacific Subtropical High Northern Boundary Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM45": {
    "standard_name": "Western Pacific Sub Tropical High Western Ridge Point Index",
    "short_name": "NCC_ATM45",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_45",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Western Pacific Sub Tropical High Western Ridge Point Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM46": {
    "standard_name": "Asia Polar Vortex Area Index",
    "short_name": "NCC_ATM46",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_46",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Asia Polar Vortex Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM47": {
    "standard_name": "Pacific Polar Vortex Area Index",
    "short_name": "NCC_ATM47",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_47",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Pacific Polar Vortex Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM48": {
    "standard_name": "North American Polar Vortex Area Index",
    "short_name": "NCC_ATM48",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_48",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American Polar Vortex Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM49": {
    "standard_name": "Atlantic-European Polar Vortex Area Index",
    "short_name": "NCC_ATM49",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_49",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Atlantic-European Polar Vortex Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM50": {
    "standard_name": "Northern Hemisphere Polar Vortex Area Index",
    "short_name": "NCC_ATM50",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_50",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Polar Vortex Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM51": {
    "standard_name": "Asia Polar Vortex Intensity Index",
    "short_name": "NCC_ATM51",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_51",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Asia Polar Vortex Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM52": {
    "standard_name": "Pacific Polar Vortex Intensity Index",
    "short_name": "NCC_ATM52",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_52",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Pacific Polar Vortex Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM53": {
    "standard_name": "North American Polar Vortex Intensity Index",
    "short_name": "NCC_ATM53",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_53",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North American Polar Vortex Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM54": {
    "standard_name": "Atlantic-European Polar Vortex Intensity Index",
    "short_name": "NCC_ATM54",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_54",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Atlantic-European Polar Vortex Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM55": {
    "standard_name": "Northern Hemisphere Polar Vortex Intensity Index",
    "short_name": "NCC_ATM55",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_55",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Polar Vortex Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM56": {
    "standard_name": "Northern Hemisphere Polar Vortex Central Longitude Index",
    "short_name": "NCC_ATM56",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_56",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Polar Vortex Central Longitude Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM57": {
    "standard_name": "Northern Hemisphere Polar Vortex Central Latitude Index ",
    "short_name": "NCC_ATM57",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_57",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Polar Vortex Central Latitude Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM58": {
    "standard_name": "Northern Hemisphere Polar Vortex Central Intensity Index",
    "short_name": "NCC_ATM58",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_58",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Northern Hemisphere Polar Vortex Central Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM59": {
    "standard_name": "Eurasian Zonal Circulation Index",
    "short_name": "NCC_ATM59",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_59",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Eurasian Zonal Circulation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM60": {
    "standard_name": "Eurasian Meridional Circulation Index",
    "short_name": "NCC_ATM60",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_60",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Eurasian Meridional Circulation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM61": {
    "standard_name": "Asian Zonal Circulation Index",
    "short_name": "NCC_ATM61",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_61",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Asian Zonal Circulation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM62": {
    "standard_name": "Asian Meridional Circulation Index",
    "short_name": "NCC_ATM62",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_62",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Asian Meridional Circulation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM63": {
    "standard_name": "East Asian Trough Position Index",
    "short_name": "NCC_ATM63",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_63",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "East Asian Trough Position Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM64": {
    "standard_name": "East Asian Trough Intensity Index",
    "short_name": "NCC_ATM64",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_64",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "East Asian Trough Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM65": {
    "standard_name": "Tibet Plateau Region 1 Index",
    "short_name": "NCC_ATM65",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_65",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Tibet Plateau Region 1 Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM66": {
    "standard_name": "Tibet Plateau Region 2 Index",
    "short_name": "NCC_ATM66",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_66",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Tibet Plateau Region 2 Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM67": {
    "standard_name": "India-Burma Trough Intensity Index",
    "short_name": "NCC_ATM67",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_67",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "India-Burma Trough Intensity Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM68": {
    "standard_name": "Arctic Oscillation, AO",
    "short_name": "NCC_ATM68",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_68",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Arctic Oscillation, AO",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM69": {
    "standard_name": "Antarctic Oscillation, AAO",
    "short_name": "NCC_ATM69",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_69",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Antarctic Oscillation, AAO",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM70": {
    "standard_name": "North Atlantic Oscillation , NAO",
    "short_name": "NCC_ATM70",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_70",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North Atlantic Oscillation , NAO",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM71": {
    "standard_name": "Pacific/ North American Pattern , PNA",
    "short_name": "NCC_ATM71",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_71",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Pacific/ North American Pattern , PNA",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM72": {
    "standard_name": "East Atlantic Pattern, EA",
    "short_name": "NCC_ATM72",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_72",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "East Atlantic Pattern, EA",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM73": {
    "standard_name": "West Pacific Pattern, WP",
    "short_name": "NCC_ATM73",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_73",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "West Pacific Pattern, WP",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM74": {
    "standard_name": "North Pacific Pattern, NP",
    "short_name": "NCC_ATM74",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_74",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "North Pacific Pattern, NP",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM75": {
    "standard_name": "East Atlantic-West Russia Pattern, EA/WR",
    "short_name": "NCC_ATM75",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_75",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "East Atlantic-West Russia Pattern, EA/WR",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM76": {
    "standard_name": "Tropical-Northern Hemisphere Pattern, TNH",
    "short_name": "NCC_ATM76",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_76",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Tropical-Northern Hemisphere Pattern, TNH",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM77": {
    "standard_name": "Polar-Eurasia Pattern, POL",
    "short_name": "NCC_ATM77",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_77",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Polar-Eurasia Pattern, POL",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM78": {
    "standard_name": "Scandinavia Pattern, SCA",
    "short_name": "NCC_ATM78",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_78",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Scandinavia Pattern, SCA",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM80": {
    "standard_name": "30hPa zonal wind Index",
    "short_name": "NCC_ATM80",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_80",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "30hPa zonal wind Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM81": {
    "standard_name": "50 hPa zonal wind Index",
    "short_name": "NCC_ATM81",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_81",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "50 hPa zonal wind Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM82": {
    "standard_name": "Mid-Eastern Pacific 200mb Zonal Wind Index ",
    "short_name": "NCC_ATM82",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_82",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Mid-Eastern Pacific 200mb Zonal Wind Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM83": {
    "standard_name": "West Pacific 850mb Trade Wind Index ",
    "short_name": "NCC_ATM83",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_83",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "West Pacific 850mb Trade Wind Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM84": {
    "standard_name": " Central Pacific 850mb Trade Wind Index",
    "short_name": "NCC_ATM84",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_84",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": " Central Pacific 850mb Trade Wind Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM85": {
    "standard_name": "East Pacific 850mb Trade Wind Index",
    "short_name": "NCC_ATM85",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_85",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "East Pacific 850mb Trade Wind Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM86": {
    "standard_name": "Atlantic-European Circulation W Pattern Index",
    "short_name": "NCC_ATM86",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_86",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Atlantic-European Circulation W Pattern Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_ATM87": {
    "standard_name": "Atlantic-European Circulation C Pattern Index",
    "short_name": "NCC_ATM87",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_ATM_ID_87",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Atm_Nc.txt",
    "description": "Atlantic-European Circulation C Pattern Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE1": {
    "standard_name": "NINO 1+2 SSTA Index",
    "short_name": "NCC_OCE1",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_1",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO 1+2 SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE2": {
    "standard_name": "NINO 3 SSTA Index",
    "short_name": "NCC_OCE2",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_2",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO 3 SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE3": {
    "standard_name": "NINO 4 SSTA Index",
    "short_name": "NCC_OCE3",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_3",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO 4 SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE4": {
    "standard_name": "NINO 3.4 SSTA Index",
    "short_name": "NCC_OCE4",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_4",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO 3.4 SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE5": {
    "standard_name": "NINO W SSTA Index",
    "short_name": "NCC_OCE5",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_5",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO W SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE6": {
    "standard_name": "NINO C SSTA Index",
    "short_name": "NCC_OCE6",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_6",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO C SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE7": {
    "standard_name": "NINO A SSTA Index",
    "short_name": "NCC_OCE7",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_7",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO A SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE8": {
    "standard_name": "NINO B SSTA Index",
    "short_name": "NCC_OCE8",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_8",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO B SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE9": {
    "standard_name": "NINO Z SSTA Index",
    "short_name": "NCC_OCE9",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_9",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "NINO Z SSTA Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE10": {
    "standard_name": "Tropical Northern Atlantic SST Index",
    "short_name": "NCC_OCE10",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_10",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Tropical Northern Atlantic SST Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE11": {
    "standard_name": "Tropical Southern Atlantic SST Index",
    "short_name": "NCC_OCE11",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_11",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Tropical Southern Atlantic SST Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE12": {
    "standard_name": "Western Hemisphere Warm Pool Index",
    "short_name": "NCC_OCE12",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_12",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Western Hemisphere Warm Pool Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE13": {
    "standard_name": "Indian Ocean Warm Pool Area Index ",
    "short_name": "NCC_OCE13",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_13",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Indian Ocean Warm Pool Area Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE14": {
    "standard_name": "Indian Ocean Warm Pool Strength Index",
    "short_name": "NCC_OCE14",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_14",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Indian Ocean Warm Pool Strength Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE15": {
    "standard_name": "Western Pacific Warm Pool Area Index",
    "short_name": "NCC_OCE15",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_15",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Western Pacific Warm Pool Area Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE16": {
    "standard_name": "Western Pacific Warm Pool Strength index",
    "short_name": "NCC_OCE16",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_16",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Western Pacific Warm Pool Strength index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE17": {
    "standard_name": "Atlantic Multi-decadal Oscillation Index",
    "short_name": "NCC_OCE17",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_17",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Atlantic Multi-decadal Oscillation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE18": {
    "standard_name": "Oyashio Current SST Index",
    "short_name": "NCC_OCE18",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_18",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Oyashio Current SST Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE19": {
    "standard_name": "West Wind Drift Current SST Index",
    "short_name": "NCC_OCE19",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_19",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "West Wind Drift Current SST Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE20": {
    "standard_name": "Kuroshio Current SST Index",
    "short_name": "NCC_OCE20",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_20",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Kuroshio Current SST Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE21": {
    "standard_name": "ENSO Modoki Index ",
    "short_name": "NCC_OCE21",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_21",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "ENSO Modoki Index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE22": {
    "standard_name": "Warm-pool ENSO Index",
    "short_name": "NCC_OCE22",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_22",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Warm-pool ENSO Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE23": {
    "standard_name": "Cold-tongue ENSO Index",
    "short_name": "NCC_OCE23",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_23",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Cold-tongue ENSO Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE24": {
    "standard_name": "Indian Ocean Basin-Wide Index",
    "short_name": "NCC_OCE24",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_24",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Indian Ocean Basin-Wide Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE25": {
    "standard_name": "Tropic Indian Ocean Dipole Index",
    "short_name": "NCC_OCE25",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_25",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "Tropic Indian Ocean Dipole Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_OCE26": {
    "standard_name": "South Indian Ocean Dipole Index",
    "short_name": "NCC_OCE26",
    "temporal_coverage": "1951-2025",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_OCE_ID_26",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Oce_Er.txt",
    "description": "South Indian Ocean Dipole Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT2": {
    "standard_name": "Western North Pacific Typhoon number",
    "short_name": "NCC_EXT2",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_2",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Western North Pacific Typhoon number",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT3": {
    "standard_name": "Number of Landing Typhoon on China",
    "short_name": "NCC_EXT3",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_3",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Number of Landing Typhoon on China",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT4": {
    "standard_name": "Total Sunspot Number Index",
    "short_name": "NCC_EXT4",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_4",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Total Sunspot Number Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT5": {
    "standard_name": "Southern Oscillation Index",
    "short_name": "NCC_EXT5",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_5",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Southern Oscillation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT6": {
    "standard_name": "Tropical Pacific Outgoing Long Wave Radiation Index",
    "short_name": "NCC_EXT6",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_6",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Tropical Pacific Outgoing Long Wave Radiation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT7": {
    "standard_name": "Multivariate ENSO Index",
    "short_name": "NCC_EXT7",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_7",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Multivariate ENSO Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT9": {
    "standard_name": "Atlantic Meridional Mode SST Index",
    "short_name": "NCC_EXT9",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_9",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Atlantic Meridional Mode SST Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT10": {
    "standard_name": "Quasi-Biennial Oscillation Index",
    "short_name": "NCC_EXT10",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_10",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Quasi-Biennial Oscillation Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT11": {
    "standard_name": "Globally Integrated Angular Momentum Index",
    "short_name": "NCC_EXT11",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_11",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Globally Integrated Angular Momentum Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT12": {
    "standard_name": "Solar Flux Index",
    "short_name": "NCC_EXT12",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_12",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Solar Flux Index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT13": {
    "standard_name": "Equatorial Pacific 130°E-80°W Upper 300m temperature averaged anomaly index ",
    "short_name": "NCC_EXT13",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_13",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Equatorial Pacific 130°E-80°W Upper 300m temperature averaged anomaly index ",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT14": {
    "standard_name": "Equatorial Pacific 160°E-80°W Upper 300m temperature Average anomaly index",
    "short_name": "NCC_EXT14",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_14",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Equatorial Pacific 160°E-80°W Upper 300m temperature Average anomaly index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT15": {
    "standard_name": "Equatorial Pacific 180º-100ºW Upper 300m temperature Average anomaly index",
    "short_name": "NCC_EXT15",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_15",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "Equatorial Pacific 180º-100ºW Upper 300m temperature Average anomaly index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  },
  "NCC_EXT16": {
    "standard_name": "North Atlantic Triple index",
    "short_name": "NCC_EXT16",
    "temporal_coverage": "1951-2021",
    "temporal_resolution": "Monthly",
    "file_name": "NCC_EXT_ID_16",
    "update_link": "http://cmdp.ncc-cma.net/download/Monitoring/Index/M_Ext.txt",
    "description": "North Atlantic Triple index",
    "web_link": "http://cmdp.ncc-cma.net/Monitoring/cn_index_130.php",
    "Source": "NCC"
  }
}
