EXT_indices_info = {
'amoc_mean': {'standard_name': 'ocean_meridional_overturning_streamfunction',
'short_name': 'amoc_mean',
'temporal_coverage': '1993-2019',
'temporal_resolution': 'Monthly',
'file_name': 'amoc_mean',
'update_link': 'https://data.marine.copernicus.eu/product/GLOBAL_OMI_NATLANTIC_amoc_max26N_timeseries/files?subdataset=global_omi_natlantic_amoc_max26N_timeseries_202207',
'description': 'Ensemble Mean of Atlantic Meridional Overturning Circulation strength (maxiumum at 26.5N)',
'web_link': 'http://marine.copernicus.eu',
'Source': 'Copernicus Marine Data Store'},
'amoc_std': {'standard_name': 'ocean_meridional_overturning_streamfunction',
'short_name': 'amoc_std',
'temporal_coverage': '1993-2019',
'temporal_resolution': 'Monthly',
'file_name': 'amoc_std',
'update_link': 'https://data.marine.copernicus.eu/product/GLOBAL_OMI_NATLANTIC_amoc_max26N_timeseries/files?subdataset=global_omi_natlantic_amoc_max26N_timeseries_202208',
'description': 'Ensemble Standard Deviation of Atlantic Meridional Overturning Circulation strength (maxiumum at 26.5N)',
'web_link': 'http://marine.copernicus.eu',
'Source': 'Copernicus Marine Data Store'},
'amoc_cglo': {'standard_name': 'ocean_meridional_overturning_streamfunction',
'short_name': 'amoc_cglo',
'temporal_coverage': '1993-2019',
'temporal_resolution': 'Monthly',
'file_name': 'amoc_cglo',
'update_link': 'https://data.marine.copernicus.eu/product/GLOBAL_OMI_NATLANTIC_amoc_max26N_timeseries/files?subdataset=global_omi_natlantic_amoc_max26N_timeseries_202209',
'description': 'Atlantic Meridional Overturning Circulation strength from C-GLORS maxiumum at 26.5N',
'web_link': 'http://marine.copernicus.eu',
'Source': 'Copernicus Marine Data Store'},
'amoc_glos': {'standard_name': 'ocean_meridional_overturning_streamfunction',
'short_name': 'amoc_glos',
'temporal_coverage': '1993-2019',
'temporal_resolution': 'Monthly',
'file_name': 'amoc_glos',
'update_link': 'https://data.marine.copernicus.eu/product/GLOBAL_OMI_NATLANTIC_amoc_max26N_timeseries/files?subdataset=global_omi_natlantic_amoc_max26N_timeseries_202210',
'description': 'Atlantic Meridional Overturning Circulation strength from GLOSEA5 maxiumum at 26.5N',
'web_link': 'http://marine.copernicus.eu',
'Source': 'Copernicus Marine Data Store'},
'amoc_glor': {'standard_name': 'ocean_meridional_overturning_streamfunction',
'short_name': 'amoc_glor',
'temporal_coverage': '1993-2019',
'temporal_resolution': 'Monthly',
'file_name': 'amoc_glor',
'update_link': 'https://data.marine.copernicus.eu/product/GLOBAL_OMI_NATLANTIC_amoc_max26N_timeseries/files?subdataset=global_omi_natlantic_amoc_max26N_timeseries_202211',
'description': 'Atlantic Meridional Overturning Circulation strength from GLORYS2V4 maxiumum at 26.5N',
'web_link': 'http://marine.copernicus.eu',
'Source': 'Copernicus Marine Data Store'},
'amoc_oras': {'standard_name': 'ocean_meridional_overturning_streamfunction',
'short_name': 'amoc_oras',
'temporal_coverage': '1993-2019',
'temporal_resolution': 'Monthly',
'file_name': 'amoc_oras',
'update_link': 'https://data.marine.copernicus.eu/product/GLOBAL_OMI_NATLANTIC_amoc_max26N_timeseries/files?subdataset=global_omi_natlantic_amoc_max26N_timeseries_202212',
'description': 'Atlantic Meridional Overturning Circulation strength from ORAS5 maxiumum at 26.5N',
'web_link': 'http://marine.copernicus.eu',
'Source': 'Copernicus Marine Data Store'},
'SAM_Station': {'standard_name': 'Marshall Southern Annular Mode (SAM) Index (Station-based)',
'short_name': 'SAM_Station',
'temporal_coverage': '1957-2024',
'temporal_resolution': 'Monthly',
'file_name': 'sam.station',
'update_link': 'https://legacy.bas.ac.uk/met/gjma/sam.html',
'description': 'Marshall Southern Annular Mode (SAM) Index (Station-based)',
'web_link': 'https://climatedataguide.ucar.edu/climate-data/marshall-southern-annular-mode-sam-index-station-based',
'Source': 'Marshall'},
'SAM_20CRV3': {'standard_name': 'Southern Annular Mode (SAM) Index (20CRV3-based)',
'short_name': 'SAM_20CRV3',
'temporal_coverage': '1836-2015',
'temporal_resolution': 'Monthly',
'file_name': 'sam.20crv3.long.data',
'update_link': 'https://psl.noaa.gov/data/20thC_Rean/timeseries/monthly/SAM/sam.20crv3.long.data',
'description': 'Southern Annular Mode (SAM) Index (20CRV3-based)',
'web_link': 'https://psl.noaa.gov/data/20thC_Rean/timeseries/monthly/SAM/',
'Source': 'NOAA/PSL'},
'SAM_20crv2c': {'standard_name': 'Southern Annular Mode (SAM) Index (20crv2c-based)',
'short_name': 'SAM_20crv2c',
'temporal_coverage': '1851-2011',
'temporal_resolution': 'Monthly',
'file_name': 'sam.20crv2c.long.data',
'update_link': 'https://psl.noaa.gov/data/20thC_Rean/timeseries/monthly/SAM/sam.20crv2c.long.data',
'description': 'Southern Annular Mode (SAM) Index (20crv2c-based)',
'web_link': 'https://psl.noaa.gov/data/20thC_Rean/timeseries/monthly/SAM/',
'Source': 'NOAA/PSL'},
'PJ_huang04': {'standard_name': 'Pacific-Japan teleconnection index defined by Huang04',
'short_name': 'PJ_huang04',
'temporal_coverage': '1940-2024',
'temporal_resolution': 'Monthly',
'file_name': 'PJ_huang04',
'update_link': 'N/A',
'description': 'N/A',
'web_link': 'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023GL106982',
'Source': 'Wenshuo Huang'},
'PJ_noh21': {'standard_name': 'Pacific-Japan teleconnection index defined by Noh21',
'short_name': 'PJ_noh21',
'temporal_coverage': '1940-2024',
'temporal_resolution': 'Monthly',
'file_name': 'PJ_noh21',
'update_link': 'N/A',
'description': 'N/A',
'web_link': 'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023GL106982',
'Source': 'Wenshuo Huang'},
'PJ_ling22': {'standard_name': 'Pacific-Japan teleconnection index defined by ling21',
'short_name': 'PJ_ling22',
'temporal_coverage': '1940-2024',
'temporal_resolution': 'Monthly',
'file_name': 'PJ_ling22',
'update_link': 'N/A',
'description': 'N/A',
'web_link': 'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023GL106982',
'Source': 'Wenshuo Huang'},
'SINTEX_ATL3': {'standard_name': 'the Atlantic Niño index (ATL3)',
'short_name': 'SINTEX_ATL3',
'temporal_coverage': '1982-2024',
'temporal_resolution': 'Monthly',
'file_name': 'SINTEX_ATL3',
'update_link': 'https://www.jamstec.go.jp/virtualearth/data/SINTEX/SINTEX_ATL3.csv',
'description': 'defined by Zebiak et al.[1993] as the area-averaged SST anomaly over the domain (3°S–3°N, 20°W–Eq.).',
'web_link': 'https://www.jamstec.go.jp/aplinfo/sintexf/e/seasonal/data_download.html',
'Source': 'JAMSTEC-SINTEX-F'},
'SINTEX_CNI': {'standard_name': 'the California Niño index (CNI)',
'short_name': 'SINTEX_CNI',
'temporal_coverage': '1982-2024',
'temporal_resolution': 'Monthly',
'file_name': 'SINTEX_CNI',
'update_link': 'https://www.jamstec.go.jp/virtualearth/data/SINTEX/SINTEX_CNI.csv',
'description': 'defined by Yuan and Yamagata [2014] as the SST anomaly averaged over the domain (240°E–250°E, 20°N–30°N).',
'web_link': 'https://www.jamstec.go.jp/aplinfo/sintexf/e/seasonal/data_download.html',
'Source': 'JAMSTEC-SINTEX-F'},
'SINTEX_DNI': {'standard_name': 'the Dakar Ninño index (DNI)',
'short_name': 'SINTEX_DNI',
'temporal_coverage': '1982-2024',
'temporal_resolution': 'Monthly',
'file_name': 'SINTEX_DNI',
'update_link': 'https://www.jamstec.go.jp/virtualearth/data/SINTEX/SINTEX_DNI.csv',
'description': 'defined by Oettli et al. [2016] as the SST anomaly averaged over the domain (21°–17°W, 9°–14°N)',
'web_link': 'https://www.jamstec.go.jp/aplinfo/sintexf/e/seasonal/data_download.html',
'Source': 'JAMSTEC-SINTEX-F'},
'SINTEX_NNI': {'standard_name': 'he Ningaloo Niño index (NNI)',
'short_name': 'SINTEX_NNI',
'temporal_coverage': '1982-2024',
'temporal_resolution': 'Monthly',
'file_name': 'SINTEX_NNI',
'update_link': 'https://www.jamstec.go.jp/virtualearth/data/SINTEX/SINTEX_NNI.csv',
'description': 'defined by Kataoka et al. [2014] as the SST anomaly averaged over the domain (108°E–116°E, 28°S–22°S)',
'web_link': 'https://www.jamstec.go.jp/aplinfo/sintexf/e/seasonal/data_download.html',
'Source': 'JAMSTEC-SINTEX-F'},
'SINTEX_SASD': {'standard_name': 'the Southern Atlantic Subtropical Dipole index (SASD)',
'short_name': 'SINTEX_SASD',
'temporal_coverage': '1982-2024',
'temporal_resolution': 'Monthly',
'file_name': 'SINTEX_SASD',
'update_link': 'https://www.jamstec.go.jp/virtualearth/data/SINTEX/SINTEX_SASD.csv',
'description': 'defined by Morioka et al. [2011] as the SST anomaly difference between the domains (330°E–350°E, 40°S–30°S) and (340°E–360°E, 25°S–15°S)',
'web_link': 'https://www.jamstec.go.jp/aplinfo/sintexf/e/seasonal/data_download.html',
'Source': 'JAMSTEC-SINTEX-F'},
'SINTEX_SIOD': {'standard_name': 'the Indian Ocean Subtropical Dipole index (SIOD)',
'short_name': 'SINTEX_SIOD',
'temporal_coverage': '1982-2024',
'temporal_resolution': 'Monthly',
'file_name': 'SINTEX_SIOD',
'update_link': 'https://www.jamstec.go.jp/virtualearth/data/SINTEX/SINTEX_SIOD.csv',
'description': 'defined by Behera and Yamagata [2001] as the SST anomaly difference between the domains (55°E–65°E, 37°S–27°S) and (90°E–100°E, 28°S–18°S)',
'web_link': 'https://www.jamstec.go.jp/aplinfo/sintexf/e/seasonal/data_download.html',
'Source': 'JAMSTEC-SINTEX-F'},
'IOBM_IRCSD': {'standard_name': 'Indian Ocean basin mode calculate by ERSSTv5',
'short_name': 'IOBM_IRCSD',
'temporal_coverage': '1854-2024',
'temporal_resolution': 'Monthly',
'file_name': 'IOBM_IRCSD',
'update_link': 'N/A',
'description': 'Indian Ocean basin mode calculate by ERSSTv5',
'reference': 'N/A',
'web_link': 'N/A',
'Source': 'huangwenshuo'}}
