# Auto-generated metadata dictionary
NOAA_indices_info = {
  "Niño 1+2 (HadISST) ": {
    "standard_name": "Niño 1+2 (HadISST) ",
    "short_name": "Niño 1+2 (HadISST) ",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "nino12.long.anom.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nino12.long.anom.data",
    "description": "Extreme Eastern Tropical Pacific SST anomaly 0N-10S, 90W-80W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino12/",
    "Source": "NOAA/PSL"
  },
  "Niño 1+2 (ERSSTv5) ": {
    "standard_name": "Niño 1+2 (ERSSTv5) ",
    "short_name": "Niño 1+2 (ERSSTv5) ",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "nina1.anom.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/nina1.anom.data",
    "description": "Extreme Eastern Tropical Pacific SST anomaly 0N-10S, 90W-80W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino12_CPC/",
    "Source": "NOAA/CPC"
  },
  "Niño 3 (HadISST)": {
    "standard_name": "Niño 3 (HadISST)",
    "short_name": "Niño 3 (HadISST)",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "nino3.long.anom.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nino3.long.anom.data",
    "description": "Eastern Tropical Pacific SST anomaly 5N-5S,150W-90W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino3/",
    "Source": "NOAA/PSL"
  },
  "Niño 3 (ERSSTv5)": {
    "standard_name": "Niño 3 (ERSSTv5)",
    "short_name": "Niño 3 (ERSSTv5)",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "nina3.anom.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/nina3.anom.data",
    "description": "Eastern Tropical Pacific SST anomaly 5N-5S,150W-90W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino3_CPC/",
    "Source": "NOAA/CPC"
  },
  "Niño 3.4 (HadISST)": {
    "standard_name": "Niño 3.4 (HadISST)",
    "short_name": "Niño 3.4 (HadISST)",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "nino34.long.anom.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nino34.long.anom.data",
    "description": "East Central Tropical Pacific SST anomaly 5N-5S,170W-120W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino34/",
    "Source": "NOAA/PSL"
  },
  "Niño 3.4 (ERSSTv5)": {
    "standard_name": "Niño 3.4 (ERSSTv5)",
    "short_name": "Niño 3.4 (ERSSTv5)",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "nina34.anom.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/nina34.anom.data",
    "description": "East Central Tropical Pacific SST anomaly 5N-5S,170W-120W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino34_CPC/",
    "Source": "NOAA/CPC"
  },
  "Niño 4 (HadISST)": {
    "standard_name": "Niño 4 (HadISST)",
    "short_name": "Niño 4 (HadISST)",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "nino4.long.anom.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nino4.long.anom.data",
    "description": "Central Tropical Pacific SST anomaly 5N-5S, 160E-150W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino4/",
    "Source": "NOAA/PSL"
  },
  "Niño 4 (ERSSTv5)": {
    "standard_name": "Niño 4 (ERSSTv5)",
    "short_name": "Niño 4 (ERSSTv5)",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "nina4.anom.data",
    "update_link": "https://psl.noaa.gov/data/correlation/nina4.anom.data",
    "description": "Central Tropical Pacific SST anomaly 5N-5S, 160E-150W",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/Nino4_CPC/",
    "Source": "NOAA/CPC"
  },
  "MEI_Extended": {
    "standard_name": "Multivariate ENSO Index (MEI Extended)",
    "short_name": "MEI_Extended",
    "temporal_coverage": "1871-2005",
    "temporal_resolution": "monthly",
    "file_name": "mei.ext.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/mei.ext.long.data",
    "description": "Original MEI extended back in time using a slightly different method. It combined atmosphere/ocean variables to produce an ENSO timeseries.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/MEI_EXTENDED/",
    "Source": "NOAA/PSL"
  },
  "MEI_V2": {
    "standard_name": "Multivariate ENSO Index V2",
    "short_name": "MEI_V2",
    "temporal_coverage": "1979-2025",
    "temporal_resolution": "monthly",
    "file_name": "meiv2.data",
    "update_link": "https://psl.noaa.gov/data/correlation/meiv2.data",
    "description": "SST and 5 atmospheric variables are combined using EOFs of the tropical Pacific to create a single index.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/MEIV2/",
    "Source": "NOAA/PSL"
  },
  "ONI": {
    "standard_name": "Oceanic Niño Index",
    "short_name": "ONI",
    "temporal_coverage": "1950-2026",
    "temporal_resolution": "monthly",
    "file_name": "oni.data",
    "update_link": "https://psl.noaa.gov/data/correlation/oni.data",
    "description": "Three month running mean of ERSST.v5 SST anomalies in the Niño 3.4 region, based on the 1971-2000 base period.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/ONI/",
    "Source": "NOAA/CPC"
  },
  "OLR_CTP": {
    "standard_name": "Central Tropical Pacific OLR Index",
    "short_name": "OLR_CTP",
    "temporal_coverage": "1974-2025",
    "temporal_resolution": "monthly",
    "file_name": "olr.data",
    "update_link": "https://psl.noaa.gov/data/correlation/olr.data",
    "description": "Outgoing Longwave Radiation (OLR) area averages over the central equatorial Pacific (160°E-160°W). OLR is a good measure of convection.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/OLR/ ",
    "Source": "NOAA/CPC"
  },
  "WH_WP": {
    "standard_name": "Western Hemisphere Warm Pool",
    "short_name": "WH_WP",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "whwp.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/whwp.data",
    "description": "Monthly anomaly of the ocean surface area warmer than 28.5 C in the Atlantic and eastern North Pacific. Based on HadISST and NOAA OI SST.",
    "web_link": "https://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "PAC_WP": {
    "standard_name": "Pacific Warm Pool Area Average",
    "short_name": "PAC_WP",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "pacwarm.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/pacwarm.data",
    "description": "Definition: area averaged SST: 60E-170E, 15S-15N.",
    "web_link": "https://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "PAC_WP_Long": {
    "standard_name": "Pacific Warm Pool",
    "short_name": "PAC_WP_Long",
    "temporal_coverage": "1854-2025",
    "temporal_resolution": "monthly",
    "file_name": "pacwarmpool.ersst.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/pacwarmpool.ersst.data",
    "description": "Niño 3.4 region, based on the 1971-2000 base period.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/PACWARM/ ",
    "Source": "NOAA/PSL"
  },
  "TNI": {
    "standard_name": "Trans-Niño Index",
    "short_name": "TNI",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "tni.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/tni.data",
    "description": "The TNI is an index of the east/west SST difference in the tropical Pacific ocean.",
    "web_link": "https://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "TNI_Long": {
    "standard_name": "Trans-Niño Index Long",
    "short_name": "TNI_Long",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "tni.long.data",
    "update_link": "https://psl.noaa.gov/gcos_wgsp/Timeseries/Data/tni.long.data",
    "description": "The TNI is an index of the east/west SST difference in the tropical Pacific ocean.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/TNI/",
    "Source": "NOAA/PSL"
  },
  "HeatCentraPac": {
    "standard_name": "Equatorial Central Pacific Heat Content: 160E-80W",
    "short_name": "HeatCentraPac",
    "temporal_coverage": "1979-2025",
    "temporal_resolution": "monthly",
    "file_name": "heatcentra.data",
    "update_link": "https://psl.noaa.gov/data/correlation/heatcentra.data",
    "description": "Equatorial Upper 300m temperature average anomaly based on 1981-2010 Climatology (deg C) for 160E-80W.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/HEATCENTRA/",
    "Source": "NOAA/PSL"
  },
  "BEST_long": {
    "standard_name": "Bivariate ENSO Time-series",
    "short_name": "BEST_long",
    "temporal_coverage": "1871-2003",
    "temporal_resolution": "monthly",
    "file_name": "censo.long.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/censo.long.data",
    "description": "Calculated from combining a standardized SOI and a standardized  Niño 3.4 SST timeseries. Uses the dataset (HadISST1.1) is now used to calculate  Niño 3.4 timeseries. Most recent data is based on the NOAA OI V2 SST dataset.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "BEST": {
    "standard_name": "Bivariate ENSO Time-series",
    "short_name": "BEST",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "censo.data",
    "update_link": "https://psl.noaa.gov/data/correlation/censo.data",
    "description": "SST and SOI are combined to form a single index of ENSO that incorporates the atmosphere explicitly.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/BEST/",
    "Source": "NOAA/PSL"
  },
  "AMM_WIND": {
    "standard_name": "Atlantic Meridional Mode Wind",
    "short_name": "AMM_WIND",
    "temporal_coverage": "1948-2023",
    "temporal_resolution": "monthly",
    "file_name": "ammwind.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/ammwind.data",
    "description": "Describes meridional variability in the tropical Atlantic Ocean.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/AMM/ ",
    "Source": "U of Wisconsin"
  },
  "AMM_SST": {
    "standard_name": "Atlantic Meridional Mode SST",
    "short_name": "AMM_SST",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "amm.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/amm.data",
    "description": "Describes meridional variability in the tropical Atlantic Ocean.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/AMM/ ",
    "Source": "U of Wisconsin"
  },
  "PMM_WIND": {
    "standard_name": "Pacific Meridional Mode Wind",
    "short_name": "PMM_WIND",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "pmmwind.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/pmmwind.data",
    "description": "Describes meridional variability in the tropical Pacific Ocean.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/PMM/ ",
    "Source": "U of Wisconsin"
  },
  "PMM_SST": {
    "standard_name": "Pacific Meridional Mode SST",
    "short_name": "PMM_SST",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "pmm.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/pmm.data",
    "description": "Describes meridional variability in the tropical Pacific Ocean.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/PMM/ ",
    "Source": "U of Wisconsin"
  },
  "DMI/IOD": {
    "standard_name": "Dipole Mode Index (DMI or IOD)",
    "short_name": "DMI/IOD",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "dmi.had.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/dmi.had.long.data",
    "description": "A difference in SST between the east and west tropical Indian pacific ocean.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/DMI/",
    "Source": "NOAA/PSL"
  },
  "DMI/IOD EAST": {
    "standard_name": "Dipole Mode Index (DMI or IOD) EAST",
    "short_name": "DMI/IOD EAST",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "dmieast.had.long.data",
    "update_link": "https://psl.noaa.gov/gcos_wgsp/Timeseries/Data/dmieast.had.long.data",
    "description": "A difference in SST between the east and west tropical Indian pacific ocean.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/DMI/",
    "Source": "NOAA/PSL"
  },
  "TC-NE Pacific Days": {
    "standard_name": "Hurricane: NE Pacific Days",
    "short_name": "TC-NE Pacific Days",
    "temporal_coverage": "1971-2021",
    "temporal_resolution": "monthly",
    "file_name": "hurr.nepac.days.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/hurr.nepac.days.data",
    "description": "Number of days where hurricanes are active in the Northeastern Pacific Basin.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/HURRICANE_NEPAC_DAYS/",
    "Source": "Col St Univ"
  },
  "TC-Atlantic Days": {
    "standard_name": "Hurricane : Atlantic Days",
    "short_name": "TC-Atlantic Days",
    "temporal_coverage": "1851-2022",
    "temporal_resolution": "monthly",
    "file_name": "hurr.atl.days.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/hurr.atl.days.data",
    "description": "Number of days where hurricanes are active in the Northern Atlantic Basin",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/HURRICANE_ATL_DAYS/",
    "Source": "Col St Univ"
  },
  "TC-NW Pacific Days": {
    "standard_name": "Hurricane: NW Pacific Days",
    "short_name": "TC-NW Pacific Days",
    "temporal_coverage": "1950-2021",
    "temporal_resolution": "monthly",
    "file_name": "hurr.nwpac.days.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/hurr.nwpac.days.data",
    "description": "Number of days where hurricanes are active in the Northwestern Pacific Basin.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/HURRICANE_NWPAC_DAYS/",
    "Source": "Col St Univ"
  },
  "TC-NE Pacific ACE": {
    "standard_name": "Hurricane: NE Pacific ACE",
    "short_name": "TC-NE Pacific ACE",
    "temporal_coverage": "1971-2021",
    "temporal_resolution": "monthly",
    "file_name": "hurr.nepac.ace.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/hurr.nepac.ace.data",
    "description": "Accumulated cyclone energy (ACE) in the Northeastern Pacific Basin.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/HURRICANE_NEPAC_ACE/",
    "Source": "Col St Univ"
  },
  "TC-Atlantic ACE": {
    "standard_name": "Hurricane: Atlantic ACE",
    "short_name": "TC-Atlantic ACE",
    "temporal_coverage": "1851-2022",
    "temporal_resolution": "monthly",
    "file_name": "hurr.atl.ace.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/hurr.atl.ace.data",
    "description": "Accumulated cyclone energy (ACE) in the Northern Atlantic Basin.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/HURRICANE_ATL_ACE/",
    "Source": "Col St Univ"
  },
  "TC-NW Pacific ACE": {
    "standard_name": "Hurricane: NW Pacific ACE",
    "short_name": "TC-NW Pacific ACE",
    "temporal_coverage": "1950-2021",
    "temporal_resolution": "monthly",
    "file_name": "hurr.nwpac.ace.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/hurr.nwpac.ace.data",
    "description": "Accumulated cyclone energy (ACE) in the Northwestern Pacific Basin.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/HURRICANE_NWPAC_ACE/",
    "Source": "Col St Univ"
  },
  "NPGO": {
    "standard_name": "North Pacific Gyre Oscillation",
    "short_name": "NPGO",
    "temporal_coverage": "1950-2025",
    "temporal_resolution": "monthly",
    "file_name": "npgo.data",
    "update_link": "https://psl.noaa.gov/data/correlation/npgo.data",
    "description": "A climate pattern derived from sea surface heights in the NE Pacific that is associated with fluctuations in the content of the California Current and the Gulf of Alaska.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NPGO/",
    "Source": "E. Di Lorenzo"
  },
  "PDO_ENS": {
    "standard_name": "Pacific Decadal Oscillation calculate from Ensemble Mean",
    "short_name": "PDO_ENS",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "pdo.timeseries.sstens.data",
    "update_link": "https://psl.noaa.gov/pdo/data/pdo.timeseries.sstens.data",
    "description": "PDO is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/pdo/",
    "Source": "NOAA/PSL"
  },
  "PDO_ERSSTv5": {
    "standard_name": "Pacific Decadal Oscillation calculate from ERSSTv5",
    "short_name": "PDO_ERSSTv5",
    "temporal_coverage": "1854-2026",
    "temporal_resolution": "monthly",
    "file_name": "pdo.timeseries.ersstv5.data",
    "update_link": "https://psl.noaa.gov/pdo/data/pdo.timeseries.ersstv5.data",
    "description": "PDO is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/pdo/",
    "Source": "NOAA/PSL"
  },
  "PDO_HadISST_1.1": {
    "standard_name": "Pacific Decadal Oscillation calculate from HadISST 1.1",
    "short_name": "PDO_HadISST_1.1",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "pdo.timeseries.hadisst1-1.data",
    "update_link": "https://psl.noaa.gov/pdo/data/pdo.timeseries.hadisst1-1.data",
    "description": "PDO is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/pdo/",
    "Source": "NOAA/PSL"
  },
  "PDO_COBE2": {
    "standard_name": "Pacific Decadal Oscillation calculate from COBE2",
    "short_name": "PDO_COBE2",
    "temporal_coverage": "1850-2026",
    "temporal_resolution": "monthly",
    "file_name": "pdo.timeseries.cobe2-sst.data",
    "update_link": "https://psl.noaa.gov/pdo/data/pdo.timeseries.cobe2-sst.data",
    "description": "PDO is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/pdo/",
    "Source": "NOAA/PSL"
  },
  "PDO_CPC": {
    "standard_name": "Pacific Decadal Oscillation from CPC",
    "short_name": "PDO_CPC",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "pdo.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/pdo.data",
    "description": "PDO is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/PDO/",
    "Source": "NOAA/PSL"
  },
  "TPI_HadISST_2": {
    "standard_name": "Tripole Index for the Interdecadal Pacific Oscillation",
    "short_name": "TPI_HadISST_2",
    "temporal_coverage": "1870-2010",
    "temporal_resolution": "monthly",
    "file_name": "ipotpi.hadisst2.data",
    "update_link": "https://www.psl.noaa.gov/data/timeseries/IPOTPI/ipotpi.hadisst2.data",
    "description": "The index is based on the difference between the SSTA averaged over the central equatorial Pacific and the average of the SSTA in the Northwest and Southwest Pacific",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/PDOUW/",
    "Source": "NOAA/PSL"
  },
  "TPI_ERSSTv5": {
    "standard_name": "TPI (IPO) Tripole Index for the Interdecadal Pacific Oscillation from ERSSTv5",
    "short_name": "TPI_ERSSTv5",
    "temporal_coverage": "1854-2026",
    "temporal_resolution": "monthly",
    "file_name": "tpi.timeseries.ersstv5.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/IPOTPI/tpi.timeseries.ersstv5.data",
    "description": "TPI is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/data/timeseries/IPOTPI/",
    "Source": "NOAA/PSL"
  },
  "TPI_HadISST_1.1": {
    "standard_name": "TPI (IPO) Tripole Index for the Interdecadal Pacific Oscillation from HadISST 1.1",
    "short_name": "TPI_HadISST_1.1",
    "temporal_coverage": "1870-2025",
    "temporal_resolution": "monthly",
    "file_name": "tpi.timeseries.hadisst11.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/IPOTPI/tpi.timeseries.hadisst11.data",
    "description": "TPI is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/data/timeseries/IPOTPI/",
    "Source": "NOAA/PSL"
  },
  "TPI_COBE": {
    "standard_name": "TPI (IPO) Tripole Index for the Interdecadal Pacific Oscillation from COBE2",
    "short_name": "TPI_COBE",
    "temporal_coverage": "1891-2023",
    "temporal_resolution": "monthly",
    "file_name": "tpi.timeseries.cobe-sst.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/IPOTPI/tpi.timeseries.cobe-sst.data",
    "description": "TPI is the leading EOF of monthly SSTA in the North Pacific, between 20N-70N. Three SST datasets are combined to create this version.",
    "web_link": "https://psl.noaa.gov/data/timeseries/IPOTPI/",
    "Source": "NOAA/PSL"
  },
  "Tropical Pacific SST EOF": {
    "standard_name": "Tropical Pacific SST EOF",
    "short_name": "Tropical Pacific SST EOF",
    "temporal_coverage": "1948-2008",
    "temporal_resolution": "monthly",
    "file_name": "eofpac.data",
    "update_link": "https://psl.noaa.gov/data/correlation/eofpac.data",
    "description": "1st EOF of SST (20N-20S, 120E-60W). GISST 1948-1949, Reconstructed Reynolds 1950-1981, OI 1982-present.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "Atlantic Tripole SST EOF": {
    "standard_name": "Atlantic Tripole SST EOF",
    "short_name": "Atlantic Tripole SST EOF",
    "temporal_coverage": "1948-2008",
    "temporal_resolution": "monthly",
    "file_name": "atltri.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/atltri.data",
    "description": "1st EOF of SST (10N-70N, 0-80W). GISST 1948-1949, Reconstructed Reynolds 1950-1981, OI 1982-present.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "AMO_NRT": {
    "standard_name": "Atlantic Multidecadal Oscillation Near-real-time",
    "short_name": "AMO_NRT",
    "temporal_coverage": "1854-2024",
    "temporal_resolution": "monthly",
    "file_name": "AMO.NRT.data",
    "update_link": "https://www1.ncdc.noaa.gov/pub/data/cmb/ersst/v5/index/ersst.v5.amo.dat",
    "description": "AMO, Near-real-time, unsmoothed. This index is newly computed from ERSSTv5",
    "web_link": "https://www1.ncdc.noaa.gov/pub/data/cmb/ersst/v5/index/ersst.v5.amo.dat",
    "Source": "NOAA/NCEI"
  },
  "AMO_us": {
    "standard_name": "Atlantic Multidecadal Oscillation, unsmoothed",
    "short_name": "AMO_us",
    "temporal_coverage": "1948-2023",
    "temporal_resolution": "monthly",
    "file_name": "amon.us.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/amon.us.data",
    "description": "AMO, unsmoothed. This index is newly computed from a new dataset and supersedes the old indices.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "AMO_sm": {
    "standard_name": "Atlantic Multidecadal Oscillation Smoothed",
    "short_name": "AMO_sm",
    "temporal_coverage": "1948-2023",
    "temporal_resolution": "monthly",
    "file_name": "amon.sm.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/amon.sm.data",
    "description": "This index is newly computed from a new dataset calculated from the Kaplan SST. The data is smoothed.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "AMO_us_long": {
    "standard_name": "Atlantic Multidecadal Oscillation, unsmoothed, long",
    "short_name": "AMO_us_long",
    "temporal_coverage": "1856-2023",
    "temporal_resolution": "monthly",
    "file_name": "amon.us.long.data",
    "update_link": "https://psl.noaa.gov/data/correlation/amon.us.long.data",
    "description": "Atlantic Multidecadal Oscillation, unsmoothed, long, calculate from  Kaplan SST dataset (5x5).",
    "web_link": "https://psl.noaa.gov/data/timeseries/AMO/",
    "Source": "NOAA/PSL"
  },
  "AMO_sm_long": {
    "standard_name": "Atlantic Multidecadal Oscillation, Smoothed, long",
    "short_name": "AMO_sm_long",
    "temporal_coverage": "1856-2023",
    "temporal_resolution": "monthly",
    "file_name": "amon.sm.long.data",
    "update_link": "https://psl.noaa.gov/data/correlation/amon.sm.long.data",
    "description": "Atlantic Multidecadal Oscillation, Smoothed, long, calculate from  Kaplan SST dataset (5x5).",
    "web_link": "https://psl.noaa.gov/data/timeseries/AMO/",
    "Source": "NOAA/PSL"
  },
  "GSL": {
    "standard_name": "Global Sea Level",
    "short_name": "GSL",
    "temporal_coverage": "1900-2018",
    "temporal_resolution": "monthly",
    "file_name": "sealevel.podaac.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/sealevel.podaac.data",
    "description": "Reconstructed global-mean sea level evolution as measured from tide-gauge.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SEALEVEL/",
    "Source": "NASA/JPL"
  },
  "AAO": {
    "standard_name": "Antarctic Oscillation from NOAA/CPC",
    "short_name": "AAO",
    "temporal_coverage": "1979-2025",
    "temporal_resolution": "monthly",
    "file_name": "aao.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/aao.data",
    "description": "Zonally symmetric oscillation calculated using the 1st EOF of 700mb height in the Southern Hemisphere south of 20S.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/AAO_CPC/",
    "Source": "NOAA/CPC"
  },
  "AO": {
    "standard_name": "Arctic Oscillation",
    "short_name": "AO",
    "temporal_coverage": "1979-2025",
    "temporal_resolution": "monthly",
    "file_name": "ao.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/ao.data",
    "description": "The AO pattern is the 1st EOF of 1000mb heights north of 20N. It measures the strength of the sea level pressure within the Arctic circle.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/AO/",
    "Source": "NOAA/CPC"
  },
  "EA/WR": {
    "standard_name": "Eastern Atlantic/Western Russia: From NOAA Climate Prediction Center (CPC)",
    "short_name": "EA/WR",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "ea.data",
    "update_link": "https://psl.noaa.gov/data/correlation/ea.data",
    "description": "The EA pattern consists of a north-south dipole of anomaly centers spanning the North Atlantic from east to west.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/EA/",
    "Source": "NOAA/CPC"
  },
  "AO_20CRv3": {
    "standard_name": "Arctic Oscillation from the 20CRv3",
    "short_name": "AO_20CRv3",
    "temporal_coverage": "1871-2012",
    "temporal_resolution": "monthly",
    "file_name": "ao.20cr.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/ao.20cr.long.data",
    "description": "The AO pattern is the 1st EOF of 1000mb heights north of 20N. It measures the strength of the sea level pressure within the Arctic circle. This version is calculated from the 20CR V3 Reanalysis",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/AO20CR/",
    "Source": "NOAA/PSL"
  },
  "Madras-SLP": {
    "standard_name": "Madras reconstructed SLP",
    "short_name": "Madras-SLP",
    "temporal_coverage": "1796-2005",
    "temporal_resolution": "monthly",
    "file_name": "madrasslp.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/madrasslp.long.data",
    "description": "Measured SLP",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/MADRAS/",
    "Source": "UEA CRU"
  },
  "NJ-SLP": {
    "standard_name": "Nakasaki Japan reconstructed SLP",
    "short_name": "NJ-SLP",
    "temporal_coverage": "1818-2000",
    "temporal_resolution": "monthly",
    "file_name": "nagasakipres.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nagasakipres.long.data",
    "description": "Measured SLP",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NAGASAKI/",
    "Source": "UEA CRU"
  },
  "NAO_AZO": {
    "standard_name": "Azores Sea Level Pressure (SLP)",
    "short_name": "NAO_AZO",
    "temporal_coverage": "1865-2002",
    "temporal_resolution": "monthly",
    "file_name": "nao_azo.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nao_azo.long.data",
    "description": "Measured SLP",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NAO_AZO/",
    "Source": "UEA CRU"
  },
  "NAO": {
    "standard_name": "North Atlantic Oscillation",
    "short_name": "NAO",
    "temporal_coverage": "1948-2022",
    "temporal_resolution": "monthly",
    "file_name": "nao.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/nao.data",
    "description": "The North Atlantic Oscillation (NAO) index is based on the surface sea-level pressure difference around the Azores and over Iceland.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/NGDC"
  },
  "NAO_ICE": {
    "standard_name": "North Atlantic Oscillation: Iceland SLP(NAO ICE)",
    "short_name": "NAO_ICE",
    "temporal_coverage": "1821-2025",
    "temporal_resolution": "monthly",
    "file_name": "nao_ice.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nao_ice.long.data",
    "description": "The North Atlantic Oscillation (NAO) index is based on the surface sea-level pressure difference around the Azores and over Iceland.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/NGDC"
  },
  "NAO_GIB": {
    "standard_name": "North Atlantic Oscillation: Gibralter SLP(NAO GIB)",
    "short_name": "NAO_GIB",
    "temporal_coverage": "1821-2025",
    "temporal_resolution": "monthly",
    "file_name": "nao_gib.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nao_gib.long.data",
    "description": "The North Atlantic Oscillation (NAO) index is based on the surface sea-level pressure difference around the Azores and over Iceland.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/NGDC"
  },
  "NAO_Jones": {
    "standard_name": "North Atlantic Oscillation (Jones)",
    "short_name": "NAO_Jones",
    "temporal_coverage": "1948-2022",
    "temporal_resolution": "monthly",
    "file_name": "jonesnao.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/jonesnao.data",
    "description": "The North Atlantic Oscillation (NAO) index is based on the surface sea-level pressure difference around the Azores and over Iceland.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/NGDC"
  },
  "NAO_CRU_Long": {
    "standard_name": "North Atlantic Oscillation from CRU",
    "short_name": "NAO_CRU_Long",
    "temporal_coverage": "1821-2024",
    "temporal_resolution": "monthly",
    "file_name": "nao.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nao.long.data",
    "description": "The North Atlantic Oscillation (NAO) index is based on the surface sea-level pressure difference around the Azores and over Iceland.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NAO/",
    "Source": "NOAA/NGDC"
  },
  "RNAO": {
    "standard_name": "Reconstructed North Atlantic Oscillation",
    "short_name": "RNAO",
    "temporal_coverage": "1658-2001",
    "temporal_resolution": "monthly",
    "file_name": "rnao.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/rnao.long.data",
    "description": "The North Atlantic Oscillation (NAO) index is based on the surface sea-level pressure difference between the Subtropical (Azores) High and the Subpolar Low.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/RNAO/",
    "Source": "NOAA/PSL"
  },
  "EP/NP": {
    "standard_name": "East Pacific/North Pacific Oscillation",
    "short_name": "EP/NP",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "epo.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/epo.data",
    "description": "East Pacific/North Pacific Oscillation",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "NOI": {
    "standard_name": "Northern Oscillation Index",
    "short_name": "NOI",
    "temporal_coverage": "1948-2024",
    "temporal_resolution": "monthly",
    "file_name": "noi.data",
    "update_link": "https://psl.noaa.gov/data/correlation/noi.data",
    "description": "An index of pressure differences similar to the SOI but for the northern hemisphere. It is strongly related to ENSO.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NOI/",
    "Source": "NOAA/PSL"
  },
  "NP": {
    "standard_name": "North Pacific Pattern",
    "short_name": "NP",
    "temporal_coverage": "1948-2024",
    "temporal_resolution": "monthly",
    "file_name": "np.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/np.data",
    "description": "NP is the area-weighted sea level pressure over the region 30N-65N, 160E-140W.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "NP/NPI": {
    "standard_name": "North Pacific Index",
    "short_name": "NP/NPI",
    "temporal_coverage": "1899-2024",
    "temporal_resolution": "monthly",
    "file_name": "np.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/np.long.data",
    "description": "The NP Index is a measure of the Sea Level Pressure in the North Pacific Ocean. It measures long (interannual-decadal) variations.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/NP/",
    "Source": "NCAR"
  },
  "NP_20CRV3": {
    "standard_name": "North Pacific Index from the 20CRV3",
    "short_name": "NP_20CRV3",
    "temporal_coverage": "1836-2015",
    "temporal_resolution": "monthly",
    "file_name": "np.20crv3.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/np.20crv3.long.data",
    "description": "The NP Index is a measure of the Sea Level Pressure in the North Pacific Ocean. It measures long (interannual-decadal) variations. This index uses the 20CR SLP data.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/NP20CR/",
    "Source": "NOAA/PSL"
  },
  "TNA": {
    "standard_name": "Tropical Northern Atlantic Index",
    "short_name": "TNA",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "tna.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/tna.data",
    "description": "Anomaly of the average of the monthly SST from 5.5N to 23.5N and 15W to 57.5W. HadISST and NOAA OI 1x1 datasets are used to create index. Climatology is 1971-2000.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "TSA": {
    "standard_name": "Tropical Southern Atlantic Index",
    "short_name": "TSA",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "tsa.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/tsa.data",
    "description": "Anomaly of the average of the monthly SST from Eq-20S and 10E-30W. HadISST and NOAA OI 1x1 datasets are used to create index.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "NTA": {
    "standard_name": "North Tropical Atlantic SST Index",
    "short_name": "NTA",
    "temporal_coverage": "1950-2020",
    "temporal_resolution": "monthly",
    "file_name": "NTA_ersst.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/NTA_ersst.data",
    "description": "SST anomalies averaged over 60W to 20W, 6N to 18N and 20W to 10W, 6N to 10N. Data is obtained from the ERSST V3b dataset.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "CAR": {
    "standard_name": "Caribbean SST Index",
    "short_name": "CAR",
    "temporal_coverage": "1950-2020",
    "temporal_resolution": "monthly",
    "file_name": "CAR_ersst.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/CAR_ersst.data",
    "description": "The timeseries of SST anomalies averaged over the Caribbean. Data is obtained from the NOAA ERSST V3b dataset. Anomalies were calculated relative to the 1981-2010 climatology, smoothed by three months running mean procedure and projected onto 20 leading EOFs.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "PNA": {
    "standard_name": "Pacific North American Index",
    "short_name": "PNA",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "pna.data",
    "update_link": "https://psl.noaa.gov/data/correlation/pna.data",
    "description": "The PNA pattern represents an alternating pressure pattern with associated changes in the East Asian Jet.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/PNA/",
    "Source": "NOAA/CPC"
  },
  "SCAND": {
    "standard_name": "Scandinavian Index",
    "short_name": "SCAND",
    "temporal_coverage": "1950-2025",
    "temporal_resolution": "monthly",
    "file_name": "scand.data",
    "update_link": "https://psl.noaa.gov/data/correlation/scand.data",
    "description": "The Scandinavian Index is a measure of blocking over western Russia and Scandinavia.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/SCAND/",
    "Source": "NOAA/CPC"
  },
  "SOI_CRU_1866": {
    "standard_name": "Southern Oscillation Index",
    "short_name": "SOI_CRU_1866",
    "temporal_coverage": "1866-2025",
    "temporal_resolution": "monthly",
    "file_name": "soi.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/soi.long.data",
    "description": "A sea-saw oscillation of surface pressure in the western Pacific. It is defined as Tahiti minus Darwin. It is strongly related to ENSO.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/SOI/",
    "Source": "UEA CRU"
  },
  "SOI": {
    "standard_name": "Southern Oscillation Index",
    "short_name": "SOI",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "soi.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/soi.data",
    "description": "Southern Oscillation Index: From NOAA Climate Prediction Center (CPC)",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "SOI_20CRV3": {
    "standard_name": "Southern Oscillation Index from the 20CRV3",
    "short_name": "SOI_20CRV3",
    "temporal_coverage": "1836-2015",
    "temporal_resolution": "monthly",
    "file_name": "soi.20crv3.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/soi.20crv3.long.data",
    "description": "A sea-saw oscillation of surface pressure in the western Pacific. This uses the 20CRV3 data and is the grid closes to Tahiti minus the grid closest to Darwin. It is strongly related to ENSO.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/SOI20CR/",
    "Source": "NOAA/PSL"
  },
  "WP": {
    "standard_name": "West Pacific Index",
    "short_name": "WP",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "wp.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/wp.data",
    "description": "A dipole of pressure anomalies between NE Asia and the western Pacific Ocean/Asia to the south.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/WP/",
    "Source": "NOAA/CPC"
  },
  "CO2-Loa": {
    "standard_name": "CO2 at Mauna Loa",
    "short_name": "CO2-Loa",
    "temporal_coverage": "1958-2024",
    "temporal_resolution": "monthly",
    "file_name": "co2.ml.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/co2.ml.data",
    "description": "CO2 Measurements monthly averaged at the NOAA/GSL Mauna Loa station in Hawaii.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/CO2ML",
    "Source": "NOAA/GML"
  },
  "CO2-GlobalAve": {
    "standard_name": "CO2: Global Average",
    "short_name": "CO2-GlobalAve",
    "temporal_coverage": "1979-2024",
    "temporal_resolution": "monthly",
    "file_name": "co2.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/co2.long.data",
    "description": "Global Average of CO2",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/CO2/",
    "Source": "NOAA/GML"
  },
  "GBI_long": {
    "standard_name": "Greenland Blocking Index Long",
    "short_name": "GBI_long",
    "temporal_coverage": "1851-2023",
    "temporal_resolution": "monthly",
    "file_name": "gbi.mon.data",
    "update_link": "https://psl.noaa.gov/gcos_wgsp/Timeseries/Data/gbi.mon.data",
    "description": "GBI is the mean 500 hPa geopotential height for the 60-80°N, 20-80°W region. It measures blocking (winds) over Greenland",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/GBI_UL/",
    "Source": "U of Lincoln"
  },
  "GBI": {
    "standard_name": "Greenland Blocking Index (GBI)",
    "short_name": "GBI",
    "temporal_coverage": "1948-2015",
    "temporal_resolution": "monthly",
    "file_name": "gbi.data",
    "update_link": "https://psl.noaa.gov/data/correlation/gbi.data",
    "description": "GBI is the mean 500 hPa geopotential height for the 60-80°N, 20-80°W region. It measures blocking (winds) over Greenland",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/GBI/",
    "Source": "NOAA/PSL"
  },
  "GLAAM": {
    "standard_name": "Global Angular Momentum",
    "short_name": "GLAAM",
    "temporal_coverage": "1958-2014",
    "temporal_resolution": "monthly",
    "file_name": "glaam.data",
    "update_link": "https://psl.noaa.gov/data/correlation/glaam.data",
    "description": "Globally averaged angular momentum calculated using angular momentum averaged over the whole atmosphere.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/GLAAM/",
    "Source": "UEA CRU"
  },
  "MDR": {
    "standard_name": "Atlantic Main Development Region",
    "short_name": "MDR",
    "temporal_coverage": "1854-2024",
    "temporal_resolution": "monthly",
    "file_name": "mdr.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/mdr.data",
    "description": "SST's in main region of cyclone development in the Atlantic.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/MDR/",
    "Source": "NOAA/PSL"
  },
  "QBO-30mb": {
    "standard_name": "Quasi-biennial Oscillation 30mb",
    "short_name": "QBO-30mb",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "qbo.data",
    "update_link": "https://psl.noaa.gov/data/correlation/qbo.data",
    "description": "The quasi-biennial oscillation (QBO) is a quasiperiodic oscillation of the equatorial zonal wind between easterlies and westerlies in the tropical stratosphere. It is typically calculated from the zonal mean 30mb winds.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/QBO/",
    "Source": "NOAA/PSL"
  },
  "QBO-50mb": {
    "standard_name": "Quasi-biennial Oscillation 50mb",
    "short_name": "QBO-50mb",
    "temporal_coverage": "1948-2026",
    "temporal_resolution": "monthly",
    "file_name": "qbo.50mb.data",
    "update_link": "https://psl.noaa.gov/data/correlation/qbo.50mb.data",
    "description": "The quasi-biennial oscillation (QBO) is a quasiperiodic oscillation of the equatorial zonal wind between easterlies and westerlies in the tropical stratosphere. This version uses 50mb zonal winds.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/QBO50/",
    "Source": "NOAA/PSL"
  },
  "uwnd_200_troppac": {
    "standard_name": "Tropical Pacific 200mb averaged zonal winds.",
    "short_name": "uwnd_200_troppac",
    "temporal_coverage": "1948-2025",
    "temporal_resolution": "monthly",
    "file_name": "uwnd.200.troppac.data",
    "update_link": "https://psl.noaa.gov/data/correlation/uwnd.200.troppac.data",
    "description": "200mb zonal winds from 2.5S to 2.5N are averaged along the equator from 165W to 110W representing the upper equatorial zonal tropical Pacific circulation.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/TROPPACU200/",
    "Source": "NOAA/PSL"
  },
  "Brazil_Pr": {
    "standard_name": "Northeast Brazil Rainfall Anomaly",
    "short_name": "Brazil_Pr",
    "temporal_coverage": "1948-2000",
    "temporal_resolution": "monthly",
    "file_name": "brazilrain.data",
    "update_link": "https://psl.noaa.gov/data/correlation/brazilrain.data",
    "description": "A normalized index of ENSO derived by using GPCP precipitation from 2 regions; one in the eastern tropical Pacific and one over the Maritime content.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/BRAZILRAIN/",
    "Source": "NCAR"
  },
  "ENSO_Pr": {
    "standard_name": "ENSO Precipitation Index",
    "short_name": "ENSO_Pr",
    "temporal_coverage": "1979-2023",
    "temporal_resolution": "monthly",
    "file_name": "espi.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/espi.data",
    "description": "A normalized index of ENSO derived by using GPCP precipitation from 2 regions; one in the eastern tropical Pacific and one over the Maritime content.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/ESPI/",
    "Source": "U of Maryland"
  },
  "Sahel_Pr_Long": {
    "standard_name": "Sahel Standardized Rainfall Long",
    "short_name": "Sahel_Pr_Long",
    "temporal_coverage": "1901-2017",
    "temporal_resolution": "monthly",
    "file_name": "sahelrain.long.data",
    "update_link": "https://psl.noaa.gov/data/correlation/sahelrain.long.data",
    "description": "A normalized index of ENSO derived by using GPCP precipitation from 2 regions; one in the eastern tropical Pacific and one over the Maritime content.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SAHELRAIN/",
    "Source": "JISAO"
  },
  "Sahel_Pr": {
    "standard_name": "Sahel Standardized Rainfall",
    "short_name": "Sahel_Pr",
    "temporal_coverage": "1948-2017",
    "temporal_resolution": "monthly",
    "file_name": "sahelrain.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/sahelrain.data",
    "description": "Averaging region based on the rotated principal component analysis of average June through September African rainfall.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SAHELRAIN/",
    "Source": "JISAO"
  },
  "NSierra8_Pr": {
    "standard_name": "N. Sierra 8 station precipitation time-series",
    "short_name": "NSierra8_Pr",
    "temporal_coverage": "1920-2025",
    "temporal_resolution": "monthly",
    "file_name": "nsierras.8st.pcp.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nsierras.8st.pcp.data",
    "description": "A regional time-series of the Northern Sierra's precipitation.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NSIERRA/",
    "Source": "CDEC/DWR California"
  },
  "NSierra5_Pr": {
    "standard_name": "C. Sierra 5 station precipitation time-series",
    "short_name": "NSierra5_Pr",
    "temporal_coverage": "1913-2025",
    "temporal_resolution": "monthly",
    "file_name": "precip.5station.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/precip.5station.data",
    "description": "A regional time-series of the Central Sierra's precipitation.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/CSIERRA/",
    "Source": "CDEC/DWR California"
  },
  "NSierra6_Pr": {
    "standard_name": "S. Sierra 6 station precipitation time-series",
    "short_name": "NSierra6_Pr",
    "temporal_coverage": "1923-2025",
    "temporal_resolution": "monthly",
    "file_name": "precip.6station.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/precip.6station.data",
    "description": "A regional time-series of the Southern Sierra's precipitation.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SSIERRA/",
    "Source": "CDEC/DWR California"
  },
  "SWM_Pr": {
    "standard_name": "SW Monsoon Region Rainfall",
    "short_name": "SWM_Pr",
    "temporal_coverage": "1948-2010",
    "temporal_resolution": "monthly",
    "file_name": "swmonsoon.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/swmonsoon.data",
    "description": "Area Averaged Precipitation for Arizona and New Mexico calculated using NCDC's climate division dataset. Monthly precipitation values for each of the climate divisions are averaged to produce a single monthly value.",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "SWUSM_Pr_Long": {
    "standard_name": "SW US Monsoon Region precipitation",
    "short_name": "SWUSM_Pr_Long",
    "temporal_coverage": "1895-2024",
    "temporal_resolution": "monthly",
    "file_name": "swmonsoon.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/swmonsoon.long.data",
    "description": "SW Monsoon region (AZ/NM) precipitation from the US climate division dataset.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SWMONSOON/",
    "Source": "NOAA/PSL"
  },
  "CI_Pr": {
    "standard_name": "Central Indian Precipitation",
    "short_name": "CI_Pr",
    "temporal_coverage": "1948-1999",
    "temporal_resolution": "monthly",
    "file_name": "indiamon.data",
    "update_link": "https://www.psl.noaa.gov/data/correlation/indiamon.data",
    "description": "Central Indian Precipitation",
    "web_link": "http://psl.noaa.gov/data/climateindices/list/",
    "Source": "NOAA/PSL"
  },
  "UCB_Pr": {
    "standard_name": "Upper Colorado Basin precipitation",
    "short_name": "UCB_Pr",
    "temporal_coverage": "1895-2019",
    "temporal_resolution": "monthly",
    "file_name": "upperCOP.mon.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/upperCOP.mon.data",
    "description": "A regional timeseries of the Upper Colorado River basin using Global Historical Climatology Network (GHCN) data.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/UpperCOP/",
    "Source": "NOAA/PSL"
  },
  "NASA_Land_T": {
    "standard_name": "NASA Global Land Temperature",
    "short_name": "NASA_Land_T",
    "temporal_coverage": "1880-2026",
    "temporal_resolution": "monthly",
    "file_name": "nasa.land.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nasa.land.data",
    "description": "Globally averaged temperature over land using the NASA GISTEMP anomaly dataset. Land is from GHCN.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NASAGLBLT/",
    "Source": "NASA"
  },
  "NASA_Comb_T": {
    "standard_name": "NASA Global Land/Ocean Temperature",
    "short_name": "NASA_Comb_T",
    "temporal_coverage": "1880-2026",
    "temporal_resolution": "monthly",
    "file_name": "nasa.comb.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/nasa.comb.data",
    "description": "Globally averaged temperature land/ocean anomalies using the NASA GISTEMP anomaly dataset. Land is from GHCN.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NASAGLBCOMT/",
    "Source": "NASA"
  },
  "Berk_Land_T": {
    "standard_name": "Berkeley Global Land Temperature",
    "short_name": "Berk_Land_T",
    "temporal_coverage": "1750-2026",
    "temporal_resolution": "monthly",
    "file_name": "Berk.land.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/Berk.land.long.data",
    "description": "Globally averaged temperature anomalies over land from Berkeley Earth.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/BERKELEYGLBLT/",
    "Source": "Berkeley Earth"
  },
  "Berk_Comb_T": {
    "standard_name": "Berkeley Global Land/Ocean Temperature",
    "short_name": "Berk_Comb_T",
    "temporal_coverage": "1850-2024",
    "temporal_resolution": "monthly",
    "file_name": "Berk.comb.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/Berk.comb.long.data",
    "description": "Globally averaged land/ocean temperature anomalies from Berkeley Earth. Ocean is from HadSST3.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/BERKELEYGLBCOMT/",
    "Source": "Berkeley Earth"
  },
  "CRU_Land_T": {
    "standard_name": "CRU Global Land Temperature",
    "short_name": "CRU_Land_T",
    "temporal_coverage": "1850-2025",
    "temporal_resolution": "monthly",
    "file_name": "CRUTEM5.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/CRUTEM5.long.data",
    "description": "Globally averaged temperature anomalies using the CRUTEM5 land dataset",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/CRUGLBLT/",
    "Source": "UEA CRU"
  },
  "CRU_Comb_T": {
    "standard_name": "CRU Global Land/Ocean Temperature",
    "short_name": "CRU_Comb_T",
    "temporal_coverage": "1850-2025",
    "temporal_resolution": "monthly",
    "file_name": "HADCRUT5.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/HADCRUT5.long.data",
    "description": "Globally averaged land/ocean temperature anomalies using the HadCRUT5 dataset",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/CRUGLBCOMT/",
    "Source": "UEA CRU"
  },
  "NOAA_Land_T": {
    "standard_name": "NOAA Global Land Temperature",
    "short_name": "NOAA_Land_T",
    "temporal_coverage": "1850-2025",
    "temporal_resolution": "monthly",
    "file_name": "noaa.globaltmp.land.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/noaa.globaltmp.land.data",
    "description": "Globally averaged land/ocean temperature anomalies using the GHCN and NOAA ERSST v5 ocean dataset",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NOAAGLBLT/",
    "Source": "NOAA/NCEI"
  },
  "NOAA_Comb_T": {
    "standard_name": "NOAA Global Land/Ocean Temperature",
    "short_name": "NOAA_Comb_T",
    "temporal_coverage": "1850-2025",
    "temporal_resolution": "monthly",
    "file_name": "noaa.globaltmp.comb.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/noaa.globaltmp.comb.data",
    "description": "Globally averaged temperature anomalies using the GHCN land dataset and the NOAA ERSST v5 ocean dataset.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NOAAGLBCOMT/",
    "Source": "NOAA/NCEI"
  },
  "NH_Ice_Area": {
    "standard_name": "Northern Hemisphere Ice Area",
    "short_name": "NH_Ice_Area",
    "temporal_coverage": "1978-2026",
    "temporal_resolution": "monthly",
    "file_name": "n_icearea.mon.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/n_icearea.mon.data",
    "description": "Satellite derived Northern Hemisphere sea ice area, intended for use in trend analysis.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NHICE/",
    "Source": "NSIDC"
  },
  "NH_Ice_Extent": {
    "standard_name": "Northern Hemisphere Ice Extent",
    "short_name": "NH_Ice_Extent",
    "temporal_coverage": "1978-2026",
    "temporal_resolution": "monthly",
    "file_name": "n_iceextent.mon.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/n_iceextent.mon.data",
    "description": "Satellite derived Northern Hemisphere sea ice extent, intended for use in trend analysis.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/NHICE/",
    "Source": "NSIDC"
  },
  "NH_Snow_Extent": {
    "standard_name": "Northern Hemisphere Snow Cover Extent",
    "short_name": "NH_Snow_Extent",
    "temporal_coverage": "1966-2024",
    "temporal_resolution": "monthly",
    "file_name": "snowextent.nh.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/snowextent.nh.data",
    "description": "Satellite derived Northern Hemisphere snow cover extent.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SNOWNH/",
    "Source": "NOAA/NCEI"
  },
  "SH_Ice_Area": {
    "standard_name": "Southern Hemisphere Ice Area",
    "short_name": "SH_Ice_Area",
    "temporal_coverage": "1978-2026",
    "temporal_resolution": "monthly",
    "file_name": "s_icearea.mon.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/s_icearea.mon.data",
    "description": "Satellite derived Southern Hemisphere sea ice area, intended for use in trend analysis.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SHICE/",
    "Source": "NSIDC"
  },
  "SH_Ice_Extent": {
    "standard_name": "Southern Hemisphere Ice Extent",
    "short_name": "SH_Ice_Extent",
    "temporal_coverage": "1978-2026",
    "temporal_resolution": "monthly",
    "file_name": "s_iceextent.mon.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/s_iceextent.mon.data",
    "description": "Satellite derived Southern Hemisphere sea ice extent, intended for use in trend analysis.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SHICE/",
    "Source": "NSIDC"
  },
  "Sunspot_Count": {
    "standard_name": "Sunspot Count",
    "short_name": "Sunspot_Count",
    "temporal_coverage": "1749-2024",
    "temporal_resolution": "monthly",
    "file_name": "sunspot.long.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/sunspot.long.data",
    "description": "A count of observed sunspot. Observations are by eye throughout the whole time-series.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SUNSPOT/",
    "Source": "WDC-SILSO"
  },
  "Solar Flux": {
    "standard_name": "Solar Flux (10.7cm)",
    "short_name": "Solar Flux",
    "temporal_coverage": "1948-2024",
    "temporal_resolution": "monthly",
    "file_name": "solar.data",
    "update_link": "https://psl.noaa.gov/data/correlation/solar.data",
    "description": "Observed 10.7cm average monthly Solar Flux.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/SOLAR/",
    "Source": "NRC Canada"
  },
  "US_Tornado_Count": {
    "standard_name": "US Tornado Count",
    "short_name": "US_Tornado_Count",
    "temporal_coverage": "1950-2024",
    "temporal_resolution": "monthly",
    "file_name": "tornado.us.mon.data",
    "update_link": "https://psl.noaa.gov/data/correlation/tornado.us.mon.data",
    "description": "The time-series has the monthly total of observed tornadoes in the US.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/TORNADO/",
    "Source": "NOAA SPC"
  },
  "UCB_T": {
    "standard_name": "Upper Colorado Basin Temperature",
    "short_name": "UCB_T",
    "temporal_coverage": "1895-2019",
    "temporal_resolution": "monthly",
    "file_name": "upperCOT.mon.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/upperCOT.mon.data",
    "description": "The time-series has the monthly temperature averaged over the Upper Colorado River Basin using the NOAA/NCEI GHCN 5km gridded dataset.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/UpperCOT/",
    "Source": "NOAA/PSL"
  },
  "LeesFerryNatlFlow": {
    "standard_name": "Lee's Ferry Natural Streamflow (upper CO Basin Streamflow)",
    "short_name": "LeesFerryNatlFlow",
    "temporal_coverage": "1905-2017",
    "temporal_resolution": "monthly",
    "file_name": "LeesFerryNatlFlow.mon.data",
    "update_link": "https://psl.noaa.gov/data/timeseries/month/data/LeesFerryNatlFlow.mon.data",
    "description": "The time-series has the measured streamflow at Lee's Ferry and thus represents the upper Colorado Basin streamflow.",
    "web_link": "https://psl.noaa.gov/data/timeseries/month/DS/LeesFerryFlow/ ",
    "Source": "NOAA/PSL"
  }
}
